FROM python:3.11-slim as base

# Сборка зависимостей
RUN apt-get update && apt-get install -y gcc

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    libgomp1

# Install ta-lib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
    && tar -xzf ta-lib-0.4.0-src.tar.gz \
    && cd ta-lib/ \
    && ./configure --prefix=/usr \
    && make \
    && make install \
    && cd .. \
    && rm -rf ta-lib/ ta-lib-0.4.0-src.tar.gz

# Инициализация проекта
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Копирование в контейнер папок и файлов.
COPY . .

